# Paramètres DVC - CallCenterAI

prepare:
  test_size: 0.2
  random_state: 42
  min_text_length: 5
  max_text_length: 500

train_tfidf:
  max_features: 5000
  ngram_range: [1, 2]
  kernel: 'linear'
  C: 1.0
  max_iter: 1000
  class_weight: 'balanced'
